config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'home#index'
  resources :users, only: [:index, :new, :show, :edit, :update, :destroy]
  get    'signup'            => 'users#new'
  post   'signup'            => 'users#create'
  get   'instagram-signup'   => 'users#instagram_create'
  get    'login'             => 'sessions#new'
  post   'login'             => 'sessions#create'
  get 'logout'               => 'sessions#destroy'
  resources :posts, only: [:index]
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :instagram_id, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :encrypt_password
  before_save :set_gender
  after_save  :clear_password

  has_many :posts, dependent: :destroy

  scope :with_role, lambda { |role| where('? = ANY(roles)', role) }
  scope :most_followed, -> { order('followed_by DESC') }

  def self.authenticate(email, login_password)
    user = User.find_by(email: email)
    user if user && user.match_password(login_password)
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

  def is_advertiser?
    roles.include? 'advertiser'
  end

  def is_influencer?
    roles.include? 'influencer'
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def assign_role(role)
    self.roles << role
  end

  private

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

  def set_gender
    detector = GenderDetector.new(case_sensitive: false)
    if detector.get_gender(self.first_name) == :female
      self.gender = 1
    elsif detector.get_gender(self.first_name) == :male
      self.gender = 2
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  before_filter :authenticate

  private

  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      username == 'hello' && password == 'world'
    end if Rails.env.production?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @top_users = User.with_role('influencer').most_followed.limit(40).shuffle.first(8)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(param[:email], param[:password])
      flash[:notice] = 'Welcome back!'
      log_in user
      redirect_to root_path
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  private

  def param
    params[:session]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.with_role('influencer')
  end

  def show
     #TODO make this redirect to 404 page in the future when you create and style one
    redirect_to root_path unless @user = User.where(instagram_username: params[:id]).includes(:posts).first
  end

  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.assign_role(user_params[:roles])

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def instagram_create
    authenticate_instagram_user unless session[:access_token]
    if @user = get_user_info
      log_in @user
      flash[:notice] = 'You successfully logged in with Instagram!'
      redirect_to root_path
    else
      flash[:destroy] = 'This was not the correct login information'
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :company_name, :company_url, :roles)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

  def access_token
    session[:access_token] ||= @access_token
  end

  def authenticate_instagram_user
    begin
      url = 'https://api.instagram.com/oauth/access_token'
      response = HTTParty.post(url, body: default_options, timeout: 5)
      @access_token = response['access_token']
    rescue Timeout::Error
      {}
    end
  end

  def get_user_info
    url = "https://api.instagram.com/v1/users/self/?access_token=#{access_token}"
    response = HTTParty.get(url)
    create_or_update_instagram_user(response)
  end

  def create_or_update_instagram_user(user_data)
    if User.where(instagram_id: user_data['data']['id']).empty?
      user = User.new
      user.instagram_id = user_data['data']['id']
      user.assign_role('influencer')
    else
      user = User.where(instagram_id: user_data['data']['id']).first
    end
    user.instagram_username = user_data['data']['username']
    user.bio = user_data['data']['bio']
    user.personal_website = user_data['data']['website']
    user.profile_picture_url = user_data['data']['profile_picture']
    user.first_name = user_data['data']['full_name'].split(' ').first
    user.last_name = user_data['data']['full_name'].split(' ').last
    user.posts_count = user_data['data']['counts']['media']
    user.followed_by = user_data['data']['counts']['followed_by']
    user.follows = user_data['data']['counts']['follows']
    user.access_token = access_token
    user.save
    user
  end

  def default_options
    {
      client_id: Rails.application.config.client_id,
      client_secret: Rails.application.config.client_secret,
      grant_type: 'authorization_code',
      code: params[:code],
      redirect_uri: "#{Rails.application.config.domain}/instagram-signup"
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.slim
#notice= notice
.homepage-wrapper
  .l--regular.brand-color
    h1.white Fluential Homepage
    h1.white Welcome to our product placement marketplace
  .l--regular
    h1 What do we do?
    h2 1. Do you have an instagram following?
    h2 2. We connect you to advertisers that pay you to market their products.
    h2 2. You post photos, you get paid
    - unless logged_in?
      = link_to 'advertiser signup', signup_path, class: 'btn btn-default'
      = link_to 'instagram signup', "https://api.instagram.com/oauth/authorize?client_id=67963d7b1ccd4cc493d85eb144a785ee&redirect_uri=#{Rails.application.config.domain}/instagram-signup&response_type=code", class: 'btn btn-default instagram-signup'
  .l--regular.fog
    h1 What do we do?
    h1 What do we do?
    h1 What do we do?
    h1 What do we do?
    h1 What do we do?
  .l--regular.top-users
    h1 Top Users
    - @top_users.each do |user|
      = link_to user_path(id: user.instagram_username) do
        .user-container
          = image_tag user.profile_picture_url, height: 150, width: 150
          br
          = "Name: #{user.full_name}"
          br
          = "Username: #{user.instagram_username}"
          br
          = "Followers: #{user.followed_by}"
          br

app/views/layouts/_header.slim
= link_to 'Fluencial', root_path, id: 'logo'
nav
  ul.nav.navbar-nav.navbar-right
    - if logged_in?
      li= link_to "Users", '#'
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#" 
          | Account
          b.caret
          ul.dropdown-menu
            li= link_to "Profile", user_path(current_user)
            li= link_to "Settings", edit_user_path(current_user)
            li.divider
            li
              = link_to "Log out", logout_path
    - else
      li= link_to "Log in", login_path
      li= link_to 'Sign up', signup_path

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    header.navbar.navbar-inverse
      .container
        .l--content
          = render partial: 'layouts/header'

    .container
      = yield

app/views/posts/index.slim
.post-wrapper
  .l--regular.fog
    - @posts.each do |post|
      .post-container
        = image_tag post.low_resolution_url, width: 240, height: 240
        br
        = "Name: #{post.name}"
        br
        = "Likes: #{post.likes_count}"
        br
        = "Comments: #{post.comments_count}"
        br

app/views/users/_form.slim
.l--content
  .row
    .col-md-6.col-md-offset-3
      = form_for(@user) do |f|
        - if @user.errors.any?
          #error_explanation
            h2
              = pluralize(@user.errors.count, "error")
              | prohibited this user from being saved:
            ul
              - @user.errors.full_messages.each do |message|
                li= message
        = f.label :first_name
        = f.text_field :first_name, class: 'form-control'
        = f.label :last_name
        = f.text_field :last_name, class: 'form-control'
        = f.label :email
        = f.email_field :email, class: 'form-control'
        = f.label :password
        = f.password_field :password, class: 'form-control'
        = f.label :company_name
        = f.text_field :company_name, class: 'form-control'
        = f.label :company_url
        = f.text_field :company_url, class: 'form-control'
        = f.submit "Sign up", class: "btn btn-primary"
      p
        | Already have an account? #{link_to "Login now!", login_path}

app/views/users/_signup_form.slim
.l--content
  .row
    .col-md-6.col-md-offset-3
      = form_for(@user, url: signup_path) do |f|
        - if @user.errors.any?
          #error_explanation
            h2
              = pluralize(@user.errors.count, "error")
              | prohibited this user from being saved:
            ul
              - @user.errors.full_messages.each do |message|
                li= message
        = f.label :first_name
        = f.text_field :first_name, class: 'form-control'
        = f.label :last_name
        = f.text_field :last_name, class: 'form-control'
        = f.label :email
        = f.email_field :email, class: 'form-control'
        = f.label :password
        = f.password_field :password, class: 'form-control'
        = f.label :company_name
        = f.text_field :company_name, class: 'form-control'
        = f.label :company_url
        = f.text_field :company_url, class: 'form-control'
        = f.hidden_field :roles, value: 'advertiser'
        = f.submit "Sign up", class: "btn btn-primary"
      p
        | Already have an account? #{link_to "Login now!", login_path}

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.slim
.homepage-wrapper
  .l--regular.top-users
    h1 Top Users
    - @users.each do |user|
      = link_to user_path(id: user.instagram_username) do
        .user-container
          = image_tag user.profile_picture_url, height: 150, width: 150
          br
          = "Name: #{user.full_name}"
          br
          = "Username: #{user.instagram_username}"
          br
          = "Followers: #{user.followed_by}"
          br

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'signup_form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.slim
.post-wrapper
  .l--regular.fog
    .user-container
      = image_tag @user.profile_picture_url, height: 300, width: 300
      br
      = "Name: #{@user.full_name}"
      br
      = "Instagram username: #{@user.instagram_username}"
      br
      = "Followers: #{@user.followed_by}"
      br

  .l--regular.fog
    - @user.posts.each do |post|
      .post-container
        = image_tag post.low_resolution_url, width: 240, height: 240
        br
        = "Name: #{post.name}"
        br
        = "Likes: #{post.likes_count}"
        br
        = "Comments: #{post.comments_count}"
        br